spring:
  datasource:
#    url: ${P2_DB_URL}
#    username: ${P2_DB_USER}
#    password: ${P2_DB_PASS}

    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  jackson:
    serialization:
      fail-on-empty-beans: false
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"